title: OPENDATA4AI
greeting: 中国AI数据开放计划
description: 我们旨在促进中国人工智能数据的开放、规范、负责任流通
logo: /img/jkan.png
hero_image: /img/homepage-hero.jpg

# Site theme
jkan_theme: Default

# Dataset schema
schema: default

# Nav bar
navigation:
  - title: AI数据索引
    url: /datasets/
  - title: AI数据调研(2022)
    url: /organizations/
  - title: AI数据协议（木兰-白玉兰协议）
    url: /categories/
  - title: 关于我们
    url: /about.html

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /organizations/:path/
  dataset_categories:
    output: true
    permalink: /categories/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: dataset_categories
    values:
      layout: category
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: false
  code: "UA-XXXXXX-1"

# Hypothesis.io - Annotator
hypothesis:
  enabled: false

# Open Graph
opengraph:
  enabled: true

# Exclude these files from the build
exclude:
  - CONTRIBUTING.md
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - scripts/src
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - netlify
  - netlify.toml
  - .parcel-cache
  - docs
